spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://database-1.c9qyy8822qo7.us-east-2.rds.amazonaws.com:3306/team
    username: admin
    password: abcdefg1
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    default-encoding: utf-8
    username: donny1848
    password: lupjmawhecxojqor
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

server:
  servlet:
    context-path: /

logging:
  level:
    org.hibernate.SQL: debug

cloud:
  aws:
    s3:
      bucket: simplelmsbucket
    stack:
      auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAU6GD2QCHXN2GMB7J
      secretKey: 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
