spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://database-1.c9qyy8822qo7.us-east-2.rds.amazonaws.com:3306/team
    username: team1
    password: abcdefg1
    driver-class-name: com.mysql.cj.jdbc.Driver
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
server:
  servlet:
    context-path: /

logging:
  level:
    org.hibernate.SQL: debug
